module.exports = {
  SELF: 'SELF',
  METRICS: 'METRICS',
  INFRASTRUCTURE: 'INFRASTRUCTURE',
  INTERNAL_DEPENDENCY: 'INTERNAL_DEPENDENCY',
  EXTERNAL_DEPENDENCY: 'EXTERNAL_DEPENDENCY',
  INTERNET_CONNECTIVITY: 'INTERNET_CONNECTIVITY'
}
